#include <facetos/dominit0/auth.h>
#include <facetos/dominit0/environment.h>
#include <facetos/sha256.h>
#include <facetos/interfaces/IAuthService.h>
#include <facetos/interfaces/IAuthenticatedPrincipal.h>
#include <facetos/interfaces/IPrincipal.h>
#include <facetos/interfaces/ISecurityManager.h>
#include <facetos/interfaces/ISession.h>
#include <string.h>
#include <stdlib.h>

typedef struct AuthUser { const FacetConfigUser *user; IPrincipal principal; IAuthenticatedPrincipal authenticated; FacetHandle principal_handle, authenticated_handle; } AuthUser;
typedef struct Session { ISession interface; FacetHandle handle, principal; struct Session *next; } Session;
static struct { IAuthService service; ISecurityManager security; FacetHandle handle, security_handle; AuthUser *users; size_t count; Session *sessions; } auth;
static int eq(uuid_t a, uuid_t b) { return memcmp(a.bytes,b.bytes,sizeof(a.bytes))==0; }
static FacetResult ret(FacetHandle h, FacetHandle *o) { if(!o)return FACET_INVALID_ARGUMENT;*o=(FacetHandle){0};if(!h.platform)return FACET_INVALID_HANDLE;*o=h;return FACET_OK; }
static FacetResult principal_get(void *s,uuid_t iid,FacetHandle *o){AuthUser*u=s;if(eq(iid,IID_IGenericObject)||eq(iid,IID_IPrincipal))return ret(u->principal_handle,o);return FACET_NO_INTERFACE;}
static FacetResult principal_id(void*s,uuid_t*o){if(!o)return FACET_INVALID_ARGUMENT; AuthUser*u=s; memset(o,0,sizeof(*o)); memcpy(o->bytes,u->user->name,u->user->name[0]?1:0);return FACET_OK;}
static FacetResult principal_name(void*s,FacetString*o){if(!o)return FACET_INVALID_ARGUMENT;AuthUser*u=s;o->data=u->user->name;o->length=strlen(o->data);return FACET_OK;}
static FacetResult authenticated_get(void*s,uuid_t iid,FacetHandle*o){AuthUser*u=s;if(eq(iid,IID_IGenericObject)||eq(iid,IID_IAuthenticatedPrincipal))return ret(u->authenticated_handle,o);return FACET_NO_INTERFACE;}
static FacetResult authenticated_principal(void*s,FacetHandle*o){return ret(((AuthUser*)s)->principal_handle,o);}
static int export_user(AuthUser *u){if(u->authenticated_handle.platform)return 0;u->principal.self=u;u->principal.getInterface=principal_get;u->principal.getid=principal_id;u->principal.getname=principal_name;u->authenticated.self=u;u->authenticated.getInterface=authenticated_get;u->authenticated.get_principal=authenticated_principal;return libfacet_export_interface(&u->principal,&IPrincipal_MetaData,&u->principal_handle)==FACET_OK&&libfacet_export_interface(&u->authenticated,&IAuthenticatedPrincipal_MetaData,&u->authenticated_handle)==FACET_OK?0:-1;}
static FacetResult service_get(void*s,uuid_t iid,FacetHandle*o){(void)s;if(eq(iid,IID_IGenericObject)||eq(iid,IID_IAuthService))return ret(auth.handle,o);return FACET_NO_INTERFACE;}
static unsigned hex(char c){return c>='0'&&c<='9'?(unsigned)(c-'0'):(unsigned)(c-'a'+10);}
static int bytes_equal(const void *left,const void *right,size_t n){const uint8_t*a=left,*b=right;uint8_t difference=0;for(size_t i=0;i<n;i++)difference|=a[i]^b[i];return difference==0;}
static FacetResult authenticate(void*s,const FacetString*n,const FacetString*p,FacetHandle*o){(void)s;if(!n||!p||!n->data||!p->data||p->length>4096)return FACET_INVALID_ARGUMENT;uint8_t d[32],expected[32];facet_sha256((const uint8_t*)p->data,p->length,d);for(size_t i=0;i<auth.count;i++){AuthUser*u=&auth.users[i];if(strlen(u->user->name)==n->length&&bytes_equal(u->user->name,n->data,n->length)){for(unsigned j=0;j<32;j++)expected[j]=(uint8_t)((hex(u->user->password_sha256[j*2])<<4)|hex(u->user->password_sha256[j*2+1]));if(!bytes_equal(d,expected,sizeof(d)))break;if(export_user(u))return FACET_OUT_OF_MEMORY;return ret(u->authenticated_handle,o);}}if(o)*o=(FacetHandle){0};return FACET_ACCESS_DENIED;}
static FacetResult session_get(void*s,uuid_t iid,FacetHandle*o){Session*x=s;if(eq(iid,IID_IGenericObject)||eq(iid,IID_ISession))return ret(x->handle,o);return FACET_NO_INTERFACE;}
static FacetResult session_principal(void*s,FacetHandle*o){if(!o)return FACET_INVALID_ARGUMENT;*o=(FacetHandle){0};return libfacet_handle_clone(((Session*)s)->principal,o);}
static FacetResult security_get(void*s,uuid_t iid,FacetHandle*o){(void)s;if(eq(iid,IID_IGenericObject)||eq(iid,IID_ISecurityManager))return ret(auth.security_handle,o);return FACET_NO_INTERFACE;}
static FacetResult security_create(void*s,FacetHandle authenticated,FacetHandle*o){(void)s;FacetHandle owned={0};if(libfacet_handle_clone(authenticated,&owned)!=FACET_OK)return FACET_ACCESS_DENIED;IAuthenticatedPrincipal*p=libfacet_proxy_from_handle(&IAuthenticatedPrincipal_MetaData,owned);if(!p){libfacet_handle_release(owned);return FACET_ACCESS_DENIED;}FacetHandle principal={0};FacetResult r=p->get_principal(p->self,&principal);libfacet_free_proxy_client(p);if(r!=FACET_OK||!principal.platform)return FACET_ACCESS_DENIED;Session*x=calloc(1,sizeof(*x));if(!x)return FACET_OUT_OF_MEMORY;x->principal=principal;x->interface.self=x;x->interface.getInterface=session_get;x->interface.get_principal=session_principal;if(libfacet_export_interface(&x->interface,&ISession_MetaData,&x->handle)!=FACET_OK){free(x);return FACET_OUT_OF_MEMORY;}x->next=auth.sessions;auth.sessions=x;return ret(x->handle,o);}
int dominit0_auth_initialize(Dominit0SystemConfig *system){if(!system||auth.handle.platform)return -1;auth.count=system->parsed.user_count;auth.users=calloc(auth.count,sizeof(*auth.users));if(!auth.users)return -1;for(size_t i=0;i<auth.count;i++)auth.users[i].user=&system->parsed.users[i];auth.service.self=&auth;auth.service.getInterface=service_get;auth.service.authenticate=authenticate;auth.security.self=&auth;auth.security.getInterface=security_get;auth.security.create_session=security_create;if(libfacet_export_interface(&auth.service,&IAuthService_MetaData,&auth.handle)!=FACET_OK||libfacet_export_interface(&auth.security,&ISecurityManager_MetaData,&auth.security_handle)!=FACET_OK)return -1;for(size_t i=0;i<system->domain_count;i++)if(system->parsed.domains[i].authentication_source_index!=(size_t)-1&&(dominit0_environment_bind_named(system->current_domains[i]->environment,"auth",IID_IAuthService,auth.handle)!=0||dominit0_environment_bind_named(system->current_domains[i]->environment,"security",IID_ISecurityManager,auth.security_handle)!=0))return -1;return 0;}
void dominit0_auth_destroy(void){while(auth.sessions){Session*x=auth.sessions;auth.sessions=x->next;if(x->handle.platform)libfacet_unexport_interface(x->handle);if(x->principal.platform)libfacet_handle_release(x->principal);free(x);}for(size_t i=0;i<auth.count;i++){if(auth.users[i].authenticated_handle.platform)libfacet_unexport_interface(auth.users[i].authenticated_handle);if(auth.users[i].principal_handle.platform)libfacet_unexport_interface(auth.users[i].principal_handle);}if(auth.security_handle.platform)libfacet_unexport_interface(auth.security_handle);if(auth.handle.platform)libfacet_unexport_interface(auth.handle);free(auth.users);memset(&auth,0,sizeof(auth));}
