[facet]
version = 1
seat_initrd = "dominit0.initrd"

[[logging_sinks]]
name = "bochs-debug"
type = "platform.x86.bochs-debug"
required = true

[[authentication_sources]]
name = "system"
provider_domain = 0
type = "local"
required = true

[[users]]
name = "root"
password_sha256 = "f490b96d6a372fd2fd1ab87bbe272a193567d04d23f5783862a187b201273f59"
admin = true

[[seats]]
name = "seat0"
type = "serial"
server = "/FacetOS/seat-server-serial"
terminals = ["ttyS0"]

[[seats]]
name = "seat1"
type = "local"
server = "/FacetOS/seat-server-pc-console"
terminals = ["tty1", "tty2", "tty3", "tty4", "tty5"]

[[domains]]
id = 0
name = "system"
personality = "native"
domain_manager = "local"
initrd = "system.initrd"
authentication_source = "system"
logging_sinks = [
    { name = "bochs-debug", level = "debug" },
]
terminals = [
    { terminal = "seat0.ttyS0", view = "native", initial_process = "/FacetOS/FacetLogin" },
    { terminal = "seat1.tty1", view = "native", initial_process = "/FacetOS/FacetLogin" },
]

[[domains]]
id = 1
name = "example-child"
personality = "native"
domain_manager = "local"
initrd = "child.initrd"
authentication_source = "system"
logging_sinks = [
    { name = "bochs-debug", level = "info" },
]
terminals = [
    { terminal = "seat1.tty2", view = "posix", initial_process = "/bin/login" },
]
