[facet]
version = 1

[[logging_sinks]]
name = "debug"
type = "platform.sel4.debug"
required = true

[[authentication_sources]]
name = "system"
provider_domain = 0
type = "local"
required = true

[[seats]]
name = "seat0"
type = "serial"
terminals = ["ttyS0"]

[[seats]]
name = "seat1"
type = "local"
terminals = ["tty1", "tty2"]

[[domains]]
id = 0
name = "system"
personality = "native"
domain_manager = "local"
authentication_source = "system"
logging_sinks = [
    { name = "debug", level = "debug" },
]
terminals = [
    { terminal = "seat0.ttyS0", view = "native", initial_process = "/FacetOS/FacetLogin" },
    { terminal = "seat1.tty1", view = "native", initial_process = "/FacetOS/FacetLogin" },
]

[[domains]]
id = 1
name = "example-child"
personality = "native"
domain_manager = "none"
authentication_source = "system"
logging_sinks = [
    { name = "debug", level = "info" },
]
terminals = [
    { terminal = "seat1.tty2", view = "posix", initial_process = "/bin/login" },
]
